<a href="https://colab.research.google.com/github/drashtikshah/Stats/blob/main/60009210079_sds_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import stats
import statistics as st
import matplot.pyplot as plt

In [ ]:
#Question 1
import numpy as np
A = [20, 2, 7, 1, 34]
print("Arthimetic mean of A is : "+str(np.mean(A)))
A1 = np.array([20, 2, 7, 1, 34])
np.mean(A1)


Arthimetic mean of A is : 12.8


12.8

In [ ]:
#Question_2
import numpy as np
b = np.array([[14, 17, 12, 33, 44],[15, 6, 27, 8, 19],[23, 2, 54, 1, 4]])
print(b)
print(str(np.mean(b)))
print(str(np.mean(b,axis = 0)))
print(str(np.mean(n,axis = 1)))

[[14 17 12 33 44]
 [15  6 27  8 19]
 [23  2 54  1  4]]
18.6
[17.33333333  8.33333333 31.         14.         22.33333333]


NameError: ignored

In [ ]:
#Question_3
import numpy as np
C = np.array([[3, 7, 5], [8, 4, 3], [2, 4, 9]])
print(C)
print("Min",str(np.min(C)))
print("Columnwise Min",str(np.min(C, axis = 0)))
print("Rowwise Min",str(np.min(C, axis = 1)))
print("Maximise of matrix",str(np.max(C)))
print("Columnwise Max",str(np.max(C, axis = 0)))
print("Rowwise Max",str(np.max(C, axis = 1)))
print("Range",str(np.ptp(C)))
print("Columnwise Range",str(np.ptp(C, axis = 0)))
print("Rowwise Range",str(np.ptp(C, axis = 1)))